### ISSUE TITLE
The terminal color isn't change background color

### ISSUE THREAD

**Issue by inozura** [owl4ce/dotfiles#167]
The terminal color isn't change background color when I try to change the visual Mode

![2022-01-20-104345_1366x768_scrot](https://user-images.githubusercontent.com/64202802/150269506-8fc74677-7b98-4b19-aad0-4b397eaedd96.png)

**Comment by owl4ce** [comment]
First I want to get straight, URxvt **can't auto-reload** the configuration since using X resource database (xrdb), it has to **restart the app**.

Second, regarding the automation when changing themes, it won't be implemented automatically. Users must manually reverse it by

**Desktop Menu (right-click)** -> **Appearance** -> **Reverse Terminal BG/FG**

In the upcoming version 4.0, I implemented URxvt auto-reload when reversed the background and foreground colors using OSC sequences.
