### ISSUE TITLE
Rollback to Default

### ISSUE THREAD

**Issue by karvanpy** [owl4ce/dotfiles#178]
I've rsync this dotfiles, but i want to back to default setup, how can that be?

**Comment by owl4ce** [comment]
Delete manually.

**Comment by owl4ce** [comment]
I'm actually sick of why people are asking this, even though they basically should have understood that this comprehensive personal dotfile is not a single thing that doesn't affect other things. It's like installing DE or uninstalling DE manually, it's also painful isn't it? That's why what I crafted is actually lighter than that, where everything is modular for each program (which has already been explained). Everyone should understand the basics of using this which is actually very easy. I would never make a helper-script to install and uninstall, although it's efficient but it's not important to me considering it only takes one install (for learning) and forever.

**Comment by owl4ce** [comment]
# So I'm wondering ..

Why don't you like or feel uncomfortable in the end but instead deploy to a "real" machine instead of a virtual one for user experience? SMH

**Comment by owl4ce** [comment]
# So if someone likes customization especially only on cosmetics ..

Why not create their own custom environment or just use a functional DE? Then change the look accordingly at will, starting with GTK/Qt themes, and so on.

**Comment by owl4ce** [comment]
If you still want to ask, further technical questions are allowed if you feel confused.

Starts by uninstalling program dependencies, then opens your previous default setup.
