### ISSUE TITLE
A few questions regarding customizations and some issues

### ISSUE THREAD

**Issue by Partha2003** [owl4ce/dotfiles#183]
Hi, I was wondering if you could please answer a few questions of mine regarding these specific topics:

**Adding buttons for launching scripts :**

I read the tint2 config and found how you have created the buttons in `eyecandy-horizontal.artistic`

```
# Button 7
button = new
button_text = 
button_tooltip = [L] Power Menu [R] Media Menu
button_lclick_command = ~/.config/rofi/scripts/rofi-exts.sh session
button_rclick_command = ~/.config/rofi/scripts/rofi-exts.sh media
button_mclick_command = 
button_uwheel_command = 
button_dwheel_command = 
button_font = Material 17
button_font_color = #fa74b2 100
button_padding = 4 0
button_background_id = 6
button_centered = 1
button_max_icon_size = 0
```

I was wondering if i could add my own button to launch a script by creating the same but i have no idea where or how a PUA unicode could be created or stored. I was wondering if you could give me an insight on that.

**Tabs** 

To make it easier for navigation could tabs be made to include the color of the app icon to make it far easier to separate between the applications that are currently on. 

![2022-05-23-132649_1920x1080_scrot](https://user-images.githubusercontent.com/96782754/169772450-a4dd668f-efe3-400d-9ddd-8817fd8435fa.png)

I can still hover over them to get a preview but a separate color would make it easier.

**Top control buttons** 

For customizing the order of the control buttons where should i go? Because through KDE settings no changes could now be made.
I want to make it so that the buttons are always on the left for every mode and the order of the button is `Close | Maximize | Minimize`

**Splash Screens** 

I remember from the first YouTube video i think you used a splash screen with a wallpaper, i was wondering if that could be used. 
On a side note I actually cannot set a splash screen from KDE settings for some reason.

**Boot Loader**

Any thoughts on a custom boot loader to match the theming?

**System wide dark mode does not take place**

KDE settings have more issues at it seems, for KDE apps they are stuck on light mode.

![2022-05-23-135300_1920x1080_scrot](https://user-images.githubusercontent.com/96782754/169776383-21682ac4-65e1-4b0a-abb7-4b6bf3efe057.png)

Every kde based app show the same thing even though dark mode is selected.

**Icons on launcher are stuck on the KDE theme icons**

I cannot change theme for some reason they are stuck on sweetified plasma icons

![2022-05-23-135554_1920x1080_scrot](https://user-images.githubusercontent.com/96782754/169776834-857f89d0-5ea7-4cbf-8004-a53eeae9afa4.png)

I don't think not having the icons properly in the folder is an issue because the right click menu is fine.

![2022-05-23-140115_1920x1080_scrot](https://user-images.githubusercontent.com/96782754/169778451-71cacef9-be93-4c71-9bd9-25dcdf6fe7cd.png)

**Power mode adjustment with battery(Slightly Unrelated)**

I was able to add a battery icon but i was wondering if there is a way to actually have a power profile switch on the go for quick switching between performance or battery life.

**KDE and openbox issue(Unrelated)** 

A weird issue has occurred between KDE and Openbox, on just launching a session through plasma x11 all the KDE apps and settings work fine, but as soon a i launch a openbox session, all kde based applications fail to work properly. I am about to raise an issue on the Garuda forum so i hoped you could assist me on this. 

[(The Raised issue)](https://forum.garudalinux.org/t/kde-and-openbox-issue/19812)

**What DE or/and distro would you recommend for maximum compatibility ? If i were not to KDE?**

I did tried to find an answer for everything before posting this, but to no avail I am left. Hopefully you would not mind any question as too childish as somethings might be too basic to have an answer.
I would really like to thank you for creating this theme as this is one of the very first themes i saw which made me help transition to Linux!

**Comment by owl4ce** [comment]
<div align="justify">

Hi @Partha2003

# First of all, thanks for telling me all this, ..

.. and I apologize for the late reply. Let me answer based on my preferences and what I know. **^^**

## Adding buttons for launching scripts

> I was wondering if i could add my own button to launch a script by creating the same but i have no idea where or how a PUA unicode could be created or stored. I was wondering if you could give me an insight on that.

Mostly, I've used `tint2conf` to configure it, with a slight modification of **.tint2rc**. You will understand when you run it [tint2conf].

## Tabs

> To make it easier for navigation could tabs be made to include the color of the app icon to make it far easier to separate between the applications that are currently on.

Unfortunately, it's impossible to set the color by application classes. In fact, my configuration was a bit of a hack to get a perfectly round shape without the title (which should be the title with the application icon). You will understand when you run it [tint2conf].

## Top control buttons

> For customizing the order of the control buttons where should i go? Because through KDE settings no changes could now be made. I want to make it so that the buttons are always on the left for every mode and the order of the button is `Close | Maximize | Minimize`

The actual configuration is static by **xml**,

https://github.com/owl4ce/dotfiles/blob/682525fb01c844fe130be0c73bc7f4944f9ce991/.config/openbox/rc.xml#L44-L52

but completely set by shell-scripts.

https://github.com/owl4ce/dotfiles/blob/682525fb01c844fe130be0c73bc7f4944f9ce991/.config/openbox/joyful-desktop/theme-set.sh#L34-L40

https://github.com/owl4ce/dotfiles/blob/682525fb01c844fe130be0c73bc7f4944f9ce991/.config/openbox/joyful-desktop/ob-button-set.sh#L42-L54

## Splash Screens

> I remember from the first YouTube video i think you used a splash screen with a wallpaper, i was wondering if that could be used. On a side note I actually cannot set a splash screen from KDE settings for some reason.

Did you mean [SLiM](https://wiki.archlinux.org/title/SLiM)? Previously I used it only for lockscreen but not anymore because it's **deprecated**. I don't use any of it.

## Boot Loader

> Any thoughts on a custom boot loader to match the theming?

There is no. I don't use bootloader as usual because of UEFI, so I use [EFI Stub](https://wiki.gentoo.org/wiki/EFI_stub). If you want, you can use [theme for grub2](https://github.com/vinceliuice/grub2-themes).

## System-wide dark mode does not take place

> KDE settings have more issues at it seems, for KDE apps they are stuck on light mode.

Did you even know that KDE uses QT? Unfortunately I don't provide QT support, but you can take a look at [this reference](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle).

https://github.com/owl4ce/dotfiles/blob/682525fb01c844fe130be0c73bc7f4944f9ce991/.config/openbox/environment#L8-L9

## Icons on launcher are stuck on the KDE theme icons 

> I cannot change theme for some reason they are stuck on sweetified plasma icons.

Hmm, I don't know why it's managed by KDE. Don't worry, maybe the following is the solution.

```sh
$ man 1 rofi | less +/-icon-theme
```

## Power mode adjustment with battery (slightly unrelated)

> I was able to add a battery icon but i was wondering if there is a way to actually have a power profile switch on the go for quick switching between performance or battery life.

Since this is not a DE or GUI framework, most of the tools I use are various CLI tools.

**->** https://wiki.archlinux.org/title/CPU_frequency_scaling#Userspace_tools

## KDE and Openbox issue (unrelated)

> A weird issue has occurred between KDE and Openbox, on just launching a session through plasma x11 all the KDE apps and settings work fine, but as soon a i launch a openbox session, all kde based applications fail to work properly. I am about to raise an issue on the Garuda forum so i hoped you could assist me on this.

Sorry, but I don't use various GUI environments. In fact, I last used XFCE then fully migrated to OpenboxWM in 2020. **I can't help.**

## What DE or/and distro would you recommend for maximum compatibility?

> If I were not to KDE?

DE? I've already answered this above. Then, I have mentioned the recommended Linux distributions in the [README.md](https://github.com/owl4ce/dotfiles#seedling--setup).

# Let me get this straight. Why did you set up using KDE?

**This is not even KDE**, but rather **custom environment** of various configurations set by shell-scripts on top of the **OpenboxWM**.

</div>
