### ISSUE TITLE
track-change-detector is running in the background and consumes CPU [Bug]

### ISSUE THREAD

**Issue by hamadmarri** [owl4ce/dotfiles#40]
**Describe the bug**
I am not sure if it is a bug or not, but I have `.ncmpcpp/scripts/track-change-detector` running in the background and it takes about 30% of the CPU. I am not sure what this script does. Could you please explain. I already commented out the script commands.

**Expected behavior**
Not running.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Opensuse Tumbleweed.
Some packages are not found/not installed.

```
picom-git
rxvt-unicode-patched
mpc
gsimplecal
gtk2-perl
imagemagick
obmenu-generator
qt5-styleplugins
wireless_tools
```

**Additional context**
Thank you for this awesome rice

**Comment by owl4ce** [comment]
`picom` is for desktop animation (fading), shadows, and for better rendering (includes rounded corners).
https://github.com/yshui/picom

for `rxvt-unicode` try to find rxvt-unicode without `patched`

`gsimplecal` is optional, when clicking time
![2021-01-14-184629_282x237_scrot](https://user-images.githubusercontent.com/53987136/104587039-e744de00-5698-11eb-8e30-562a781641a7.png)

`gtk2-perl` is used to make the desktop menu (right click) bring up the icon.
> obmenu-generator is required
https://github.com/trizen/obmenu-generator

actually `imagemagick` and `ffmpeg` are also optional, mostly here to convert notification icon when playing song from `mpd` controlled from `ncmpcpp` + `mpc`.
![2021-01-14-184946_239x108_scrot](https://user-images.githubusercontent.com/53987136/104587326-5de1db80-5699-11eb-96a7-c35c42853f03.png)

**Comment by owl4ce** [comment]
**Hi @hamadmarri** 
I can confirm, maybe because previously on your linux there is no `mpc` but this script continues (loop) without `mpc`.
![2021-01-16-194154_894x168_scrot](https://user-images.githubusercontent.com/53987136/104812164-fc557480-5832-11eb-8754-96435a8d9771.png)

This is my mistake which should give the condition if `mpd` and `mpc` exist then continue.
#### Before
![2021-01-16-194044_349x219_scrot](https://user-images.githubusercontent.com/53987136/104812126-d203b700-5832-11eb-9f90-935e2e755007.png)

#### After
![2021-01-16-194106_434x226_scrot](https://user-images.githubusercontent.com/53987136/104812133-dcbe4c00-5832-11eb-83e8-945da05fc49b.png)

**Comment by hamadmarri** [comment]
Thank you @owl4ce
